package TrafficSim;

/**
 *
 * @author nikla_000
 */
public enum Direction {
    
    NORTH, SOUTH, WEST, EAST,
    NORTHTOSOUTH, NORTHTOEAST, NORTHTOWEST,
    EASTTOSOUTH, EASTTOWEST, EASTTONORTH,
    SOUTHTOWEST, SOUTHTONORTH, SOUTHTOEAST,
    WESTTONORTH, WESTTOEAST, WESTSOUTH;
    
}
